name: Publish to Maven Central
# ./gradlew :velo-core:tasks --all | grep publish
on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Decode GPG Key
        run: |
          echo "$SIGNING_KEY" > private.key
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Import GPG
        run: |
          gpg --batch --import private.key

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build & Publish
        run: ./gradlew publishAll --no-daemon
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - name: Set version from git tag
        run: echo "VERSION_NAME=$(git describe --tags --abbrev=0)" >> gradle.properties


